
/ULALAP/det/setOutputDirectory /sps/lbno/lmanzani/ulalap_output/Cavern_gammas/
/ULALAP/det/setSetupName file_100_dir_2
/ULALAP/det/setDetectorType 1
/ULALAP/det/setShieldingMaterialWaffle G4_AIR
/ULALAP/det/setWaffleThickness 100 cm
/ULALAP/det/setShieldingMaterial G4_Pb
/ULALAP/det/setshieldingThickness 5 cm
#select output format, options are: csv root hdf5
#ULALAP/det/setDataType csv
/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state false
/process/had/particle_hp/skip_missing_isotopes true
#direction type, if 1 isotropic
/ULALAP/gun/sourceDirectionType 2
#direction of the source
/ULALAP/gun/direction 0 1 0
#position of the center of the source in cm for x y z
/ULALAP/gun/position 0 -1050 0
#choise of the source: 0 for gamma, 1 for Fe55, 2 for Cs137, 3 for Bi207, 4 for Sr90, 5 for Am241, 6 for electron, 7 for optical_photon, 8 for neutron
/ULALAP/gun/sourceType 4
#geometry of the source: Sphere Cone Box point
/ULALAP/gun/shape Box
#size of the box in cm for x y z
/ULALAP/gun/BoxXYZ 6000 1 1400
#number of events
/run/beamOn 1000000


