/process/em/fluo true
/process/em/auger true
/process/em/augerCascade true 
/process/em/pixe true

#/G4SOS/det/setOutputDirectory /home/iwsatlas1/manzanil/Documents/Varios/SOLEIL/ 
/G4SOS/det/setDetectorType 1
/G4SOS/det/setNTargetSamples 1
/G4SOS/det/setGeDetectorThickness 2. mm
#Set the position of the collimator, a values between -37 and 37 mm (size of samples)
#Choise of source type: 0 Cs-137; 1 Bi-207; 2 Sr-90; 3 e-
/run/initialize
/G4SOS/gun/sourceType 0

/run/beamOn 1
