
/ULALAP/det/setOutputDirectory /sps/lbno/lmanzani/ulalap_output/
/ULALAP/det/setSetupName file_4_dir_2
/ULALAP/det/setDetectorType 0
/ULALAP/det/setShieldingMaterialWaffle G4_AIR
/ULALAP/det/setWaffleThickness 100 cm
/ULALAP/det/setShieldingMaterial G4_WATER
/ULALAP/det/setshieldingThickness 50 cm
#select output format, options are: csv root hdf5
#ULALAP/det/setDataType csv
/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state false
/process/had/particle_hp/skip_missing_isotopes true
#direction type, if 1 isotropic
/ULALAP/gun/sourceDirectionType 2
#direction of the source
/ULALAP/gun/direction 0 0 -1
#position of the center of the source in cm for x y z
/ULALAP/gun/position 0 0 950
#/ULALAP/gun/sourceEnergy 0.023 eV
#choise of the source: 11 for neutron spectrum
/ULALAP/gun/sourceType 11
#geometry of the source: Sphere Cone Box point
/ULALAP/gun/shape Box
#size of the box in cm for x y z
/ULALAP/gun/BoxXYZ 6000 1500 1
#number of events
/run/beamOn 500000


