#/run/numberOfThreads 4
#/ULALAP/det/setOutputDirectory /nfs/tegile/work/experiences/detecteurs/manzanillas/LEAPS_INNOV/Geant4_output/ 
#/ULALAP/det/setDetectorType 5
#select output format, options are: csv root hdf5
#ULALAP/det/setDataType csv
/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state false
/process/had/particle_hp/skip_missing_isotopes true
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
#direction type, if 1 isotropic
/ULALAP/gun/sourceDirectionType 0
#direction of the source
/ULALAP/gun/direction -1 0 0
#position of the center of the source in cm for x y z
/ULALAP/gun/position 10 20 30
/ULALAP/gun/sourceEnergy 0.023 eV
#choise of the source: 0 for gamma, 1 for Fe55, 2 for Cs137, 3 for Bi207, 4 for Sr90, 5 for Am241, 6 for electron, 7 for optical_photon, 8 for neutron
/ULALAP/gun/sourceType 8
#geometry of the source: Sphere Cone Box point
/ULALAP/gun/shape Box
#size of the box in cm for x y z
/ULALAP/gun/BoxXYZ 100 200 300
#number of events
/run/beamOn 10000
