#/run/numberOfThreads 4
#/ULALAP/det/setOutputDirectory /nfs/tegile/work/experiences/detecteurs/manzanillas/LEAPS_INNOV/Geant4_output/ 
#/ULALAP/det/setDetectorType 5
#select output format, options are: csv root hdf5
/ULALAP/det/setDataType csv
#Set the position of the collimator, a values between -37 and 37 mm (size of samples)
#Choise of source type: 0 gamma,1 Fe-55,2 Cs-137; 1 Bi-207; 2 Sr-90; 3 e-

/run/beamOn 1000
